name: bibbia_cattolica
description: A new Flutter project.

version: 1.0.0+1

environment:
    sdk: '>=3.4.3 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    cupertino_icons: ^1.0.0
    path: ^1.6.4
    provider: ^6.1.2
    flutter_svg: ^2.0.10+1
    package_info: ^2.0.2
    html: ^0.15.4
    shared_preferences: ^2.3.2
    flutter_colorpicker: ^1.1.0
    intl: ^0.19.0
    get_it: ^7.7.0
    flutter_widget_from_html: ^0.15.1
    html_unescape: ^2.0.0
    catholic_liturgy: ^0.0.17
    csv: ^6.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    enum_to_string: ^2.0.1
    flutter_lints: ^4.0.0
    mockito: ^5.4.4

flutter:
    uses-material-design: true
    assets:
        - assets/db/
        - assets/images/
        - assets/icons/
        - assets/texts/bible/
        - assets/texts/bible/italian-cei2008/
